# Generated by Django 5.0.4 on 2024-12-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
