# Generated by Django 5.0.4 on 2025-01-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_articles_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['date'], name='news_articl_date_96af77_idx'),
        ),
    ]
