# Generated by Django 5.0.4 on 2025-04-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%y/%m/%d', verbose_name='Фото'),
        ),
    ]
